[View in Colaboratory](https://colab.research.google.com/github/yashrajeshhiray/second-repo/blob/master/Begginer_codes.ipynb)

In [0]:
import tensorflow as tf

In [0]:
#this is a constant
a = tf.constant(1)

In [0]:
#this is a variable
b = tf.Variable(0)

In [0]:
#this is a new value
new_value = tf.add(a,b)

In [0]:
#update a variable
update = tf.assign(b,new_value)

In [0]:
#init_op = tf.initialize_all_variables()
init_op = tf.global_variables_initializer()

In [0]:
sess = tf.Session()



In [0]:
#initialize variables
sess.run(init_op)


In [18]:
print(sess.run(b))

0


In [0]:
for j in range(5):
  sess.run(update)
  print(sess.run(b))
  

In [0]:
#string operation

In [0]:
hello = tf.constant("hello")

In [0]:
world = tf.constant("world")

In [0]:
hello_darling = tf.add(hello,world)

In [29]:
print(sess.run(hello_darling))

b'helloworld'


In [0]:
#placeholder
pl = tf.placeholder(tf.float32)

In [0]:
c = pl*2

In [34]:
result = sess.run(c,feed_dict={pl:5})
#print result = sess.run(c,{pl:5})
print(result)

10.0


In [38]:
#feeding a placeholder with vector of rqnk 1
result = sess.run(c,feed_dict={pl:[3,4,6]})
print(result)      

[ 6.  8. 12.]


In [39]:
#feeding a placeholder with multidimensional aray
dictionary = {c:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

result = sess.run(c,feed_dict=dictionary)
print(result)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 18.]
  [19. 20. 21.]
  [22. 23. 24.]]]


In [0]:
sess.close()

In [41]:
with tf.Session() as sess:
  result = sess.run(hello+world)
  print(result)
  #all lines will be executed within this session
  #no need of explicitly closing the session

b'helloworld'
